username: "First Last"
email: test_user@fake_email.com
# ssh_path: /home/user/.ssh
# ssh_key_path: /home/user/.ssh/github_rsa
clone_base_path: /tmp
repo_name: test-repo
repository_uri: git@github.com:test_user/test-repo.git
utc_offset: -500
